const {
    VITE_BASE_URL,
    VITE_PROJECT_ID,
    VITE_E_COMMERCE_DATAASE_ID,
    VITE_PRODUCTS_COLLECTION_ID,
    VITE_CUSTOMERS_COLLECTION_ID,
    VITE_SELLERS_COLLECTION_ID,
    VITE_CATEGORIES_COLLECTION_ID,
    VITE_CART_COLLECTION_ID,
    VITE_ORDERS_COLLECTION_ID,
    VITE_PAYMENTS_COLLECTION_ID,
    VITE_LOCATIONS_COLLECTION_ID,
    VITE_SHIPPERS_COLLECTION_ID,
    VITE_PACKAGES_COLLECTION_ID,

    VITE_ADD_TO_CART_FUNCTION_ID,
    VITE_REMOVE_FROM_CART_FUNCTION_ID
} = import.meta.env;

export const ENDPOINT = VITE_BASE_URL;
export const PROJECT_ID = VITE_PROJECT_ID;

export const ECOMM_DB_ID = VITE_E_COMMERCE_DATAASE_ID;

export const PRODUCTS_ID = VITE_PRODUCTS_COLLECTION_ID;
export const CUSTOMERS_ID = VITE_CUSTOMERS_COLLECTION_ID;
export const SELLERS_ID = VITE_SELLERS_COLLECTION_ID;
export const CATEGORIES_ID = VITE_CATEGORIES_COLLECTION_ID;
export const CART_ID = VITE_CART_COLLECTION_ID;
export const ORDERS_ID = VITE_ORDERS_COLLECTION_ID;
export const PAYMENTS_ID = VITE_PAYMENTS_COLLECTION_ID;
export const LOCATIONS_ID = VITE_LOCATIONS_COLLECTION_ID;
export const SHIPPERS_ID = VITE_SHIPPERS_COLLECTION_ID;
export const PACKAGES_ID = VITE_PACKAGES_COLLECTION_ID;

export const ADD_TO_CART_FUNCTION_ID = VITE_ADD_TO_CART_FUNCTION_ID;
export const REMOVE_FROM_CART_FUNCTION_ID = VITE_REMOVE_FROM_CART_FUNCTION_ID;
